### ISSUE TITLE
why use srun command for mixtral-8x7B full finetune??

### ISSUE THREAD

**Issue by hegang1-tal** [Alpha-VLLM/LLaMA2-Accessory#138]
When  I tried to run full finetune mixtral-8x7B sparse model，I found that srun command is needed.  After installing slum-client using "apt-get install slurm-client", and then run    srun xxxxx, it failed.   does srun command is must for full finetuning  mixtral-8x7B model??

**Comment by ChrisLiu6** [comment]
SLURM is not important, what is indeed important is that 8 GPUs are generally insufficient to full finetune mixtral 8x7B, so multiple GPU nodes are needed, and SLURM is the typical tool to manage such clusters.  If you only have 8 GPUs, you may try the peft setting and use torchrun instead of srun for launching experiments; If you have access to a GPU cluster but it is not managed by SLURM, you may replace srun with platform-specific commands with similar functions.

**Comment by hegang1-tal** [comment]
thank u!  Now I can run full SFT finetuning with torchrun and 4 x 8 A100 80G GPUs.

**Comment by bao-xiaoyi** [comment]
> 感谢你！现在我可以使用 torchrun 和 4 x 8 A100 80G GPU 运行完整的 SFT 微调。

是使用的srun吗，还是用了其他命令？

**Comment by bao-xiaoyi** [comment]
> thank u! Now I can run full SFT finetuning with torchrun and 4 x 8 A100 80G GPUs.

能提供一下系统设置吗？我大约一轮快训完的时候会卡住，显存利用率和网卡通信会掉到0。
