### ISSUE TITLE
Compatibility Issue with NO-SHARD/Single GPU training

### ISSUE THREAD

**Issue by qihan96** [Alpha-VLLM/LLaMA2-Accessory#25]
Hi, I tried to run main_finetune.py file, but an Unimplemented error is triggered with load_cpu=true and NO-SHARD. Any directions to adapt the code in this situation? Your help is much appreciated.

**Comment by ChrisLiu6** [comment]
Hi! Based on my experience, this error occurs either when the `data_parallel` argument in main_finetune.py is set to `ddp`, or when the world size is set to one. Under both circumstances, sharding in FSDP is disabled, and the error you list occurs. 

I believe the root cause of this error lies primarily in the current limitations of PyTorch's FSDP functionality, which is still under active development. As a workaround for now, you can try setting [offload_to_cpu](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blame/main/accessory/util/misc.py#L347) to False, or using at least two GPUs.

**Comment by qihan96** [comment]
Hi, setting offload_to_cpu == False works. Thank you for your help!
